apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-monitoring
  labels:
    app: nginx-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-monitoring
  template:
    metadata:
      labels:
        app: nginx-monitoring
    spec:
      containers:
        - name: nginx
          image: otus-nginx-monitoring:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.4.2
          args:
            - --nginx.scrape-uri=http://127.0.0.1/stub_status
          ports:
            - name: metrics
              containerPort: 9113
