{{- if .Values.rbac.monitoring.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homework.fullname" . }}-monitoring
  labels:
    {{- include "homework.labels" . | nindent 4 }}

rules:
  - nonResourceURLs:
      - {{ .Values.rbac.monitoring.metricsPath }}
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homework.fullname" . }}-monitoring
  labels:
    {{- include "homework.labels" . | nindent 4 }}

subjects:
  - kind: ServiceAccount
    name: {{ include "homework.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homework.fullname" . }}-monitoring
{{- end }}
