adminUser: admin
adminPassword: admin

service:
  type: ClusterIP

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local
        isDefault: true

tolerations:
  - operator: Exists
